In [1]:
import pandas as pd
import numpy  as np
from numpy.random import random
from sklearn.utils import shuffle
from math import inf


names = ['sl','sw','pl','pw','class']
iris = pd.read_csv("../data/iris/iris.data",names=names)
iris.drop(columns='class',inplace=True)
iris = (iris - iris.min())/(iris.max()- iris.min())
iris = shuffle(iris)
irisV = iris.values

In [64]:
c1 = pd.Series(random(4)).values
c2 = pd.Series(random(4)).values
c3 = pd.Series(random(4)).values
c = np.array( [c1,c2,c3]  )
centroids=[np.copy(c),0]
cond = [inf,inf,inf]

d1 = np.empty(0)
d2 = np.empty(0)
d3 = np.empty(0)
distance =np.empty((3,150)) 


while all(cnd > 0.005 for cnd in cond):
    distance =np.empty((3,150))
    centroids[0] = np.copy(c)
    for j in range(3):
        d = []
        for i in range(150):   
            sub = irisV[i]-c[j] 
            temp = np.dot( np.reshape(sub,(1,4)),np.reshape(sub,(4,1))  )
            d = np.append(d , np.sqrt(temp))
        distance[j] = d
    distance = np.reshape(distance,(150,3))
    iris = iris.reset_index(drop=True)
    species = []
    
    for i in range(150):
        species.append(distance[i].argmin())
    species
    iris['species'] = species
    for i in range(3):
        c[i] = iris[iris['species']==i].mean().drop('species')
    centroids[1] = np.copy(c)
    ll=[0,0,0]
    for i in range(3):
        s = centroids[1][i] - centroids[0][i]
        temp = np.dot(  np.reshape(s,(1,4)),np.reshape(s,(4,1)))
        cond[i] = temp[0][0]


print('Centroids: \n',c)
temp = [[],[],[]]

for i in range(150):
    indx = distance[i].argmin()
    temp[indx].append(distance[i][indx])
sum  =[np.sum(temp[0]),np.sum(temp[1]),np.sum(temp[2])]
print('вектор сумм расстояний объектов кластера до его центроида: ')
print(sum)

print('матрица расстояний объектов кластера до его центроида: ')
for i in range(3):
    print(temp[i])
t

Centroids: 
 [[0.39912281 0.43932749 0.44870651 0.44225146]
 [0.48290598 0.41987179 0.51955671 0.49839744]
 [0.40108401 0.46341463 0.42786275 0.42784553]]
вектор сумм расстояний объектов кластера до его центроида: 
[20.93457764662388, 16.808025798988094, 13.510351209314875]
матрица расстояний объектов кластера до его центроида: 
[0.14271546402805219, 0.16325599705263383, 0.24477021215654907, 0.3841543901952561, 0.35417335482450674, 0.15917441985339498, 0.6637380880647515, 0.704236454167189, 0.37477874546023243, 0.5510171626082777, 0.1699700910861166, 0.28309589844713123, 0.5902252170142762, 0.4206980030077758, 0.22205146960045, 0.24100613323650144, 0.4020683345434589, 0.08550613198589223, 0.5353809803170072, 0.1643396895651838, 0.16836468148088762, 0.2606521318329375, 0.4098983381674108, 0.3571383788098018, 0.18342355496711674, 0.6368085091970885, 0.6838306928602126, 0.39404771838265484, 0.5281570452891465, 0.18216850118100034, 0.29178027841795473, 0.6150071920018214, 0.454480541028741

NameError: name 't' is not defined